apiVersion: apps/v1
kind: Deployment
metadata:
  name: edustream-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edustream-frontend
  template:
    metadata:
      labels:
        app: edustream-frontend

    spec: 
      containers:
      - name: frontend 
        image: testethical/edustream-frontend:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: edustream-frontend-service 
spec:
  selector:
    app: edustream-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort